version: '3.7'

services:

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./code:/var/www
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - ./certificate/ssl:/etc/nginx/ssl:ro,delegated
      - ./code:/var/www:ro,delegated
    # networks:
    #   snapx-network:
    #     ipv4_address: ${NGINX_IP}

  certificate:
    build:
      context: ./certificate
    container_name: certificate
    restart: unless-stopped
    tty: true
    volumes:
      - ./certificate/ssl:/home/cert/ssl
  
  npm:
    build:
      context: ./npm
    restart: unless-stopped
    tty: true
    container_name: npm
    working_dir: /var/www
    volumes:
      - ./code:/var/www